# Generated by Django 4.0.7 on 2022-12-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='album_id',
        ),
    ]
