# Generated by Django 4.0.7 on 2022-12-14 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_rename_album_song_album_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='album',
        ),
    ]
